const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto'),C=require('../extension/catalog.js');
function harness(){
 const data={},alarms=new Map(),notifications=[];let listener,onAlarm,onClick,onStartup;
 const chrome={runtime:{getURL:p=>'chrome-extension://test/'+p,onMessage:{addListener:f=>listener=f},onStartup:{addListener:f=>onStartup=f}},storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).filter(k=>data[k]!==undefined).map(k=>[k,structuredClone(data[k])])),set:async v=>Object.assign(data,structuredClone(v))}},tabs:{query:async()=>[],create:async()=>{}},alarms:{create:async(id,o)=>alarms.set(id,o),clear:async id=>alarms.delete(id),onAlarm:{addListener:f=>onAlarm=f}},notifications:{create:async(id,o)=>notifications.push({id,...o}),onClicked:{addListener:f=>onClick=f}},action:{setBadgeText:async()=>{}},scripting:{executeScript:async()=>{}}};
 vm.runInNewContext(fs.readFileSync('extension/background.js','utf8'),{chrome,TicketCatalog:C,importScripts:()=>{},URL,crypto,Date});
 const send=(msg,sender={url:'chrome-extension://test/ui/dashboard.html'})=>new Promise(resolve=>{const asyncResult=listener(msg,sender,resolve);if(!asyncResult)resolve({ignored:true});});
 return {data,alarms,notifications,send,fire:id=>onAlarm({name:id})};
}
const plan={url:'https://detail.damai.cn/item.htm?id=123456789',title:'测试演出',opensAt:'2099-09-20T12:00',quantity:1,maxTotal:'680',choices:[{session:'周六',tier:'680元'}]};
test('saving, firing twice and cancelling reminders is serialized and idempotent',async()=>{const h=harness();const r=await h.send({type:'SAVE_PLAN',plan});assert.equal(r.ok,true);const task=h.data.tasks[0];assert.equal(h.alarms.size,1);await h.fire(task.taskId);await h.fire(task.taskId);assert.equal(h.notifications.length,1);assert.equal(h.data.tasks[0].state,'notified');await h.send({type:'CANCEL',taskId:task.taskId});assert.equal(h.alarms.size,0);});
test('concurrent saves preserve both tasks',async()=>{const h=harness();await Promise.all([h.send({type:'SAVE_PLAN',plan}),h.send({type:'SAVE_PLAN',plan})]);assert.equal(h.data.tasks.length,2);assert.notEqual(h.data.tasks[0].taskId,h.data.tasks[1].taskId);});
test('web content cannot create plans or inject offsite catalog',async()=>{const h=harness();await h.send({type:'SAVE_PLAN',plan},{url:'https://detail.damai.cn/item.htm?id=123456789'});assert.equal(h.data.tasks,undefined);const r=await h.send({type:'CATALOG_CAPTURE',records:[plan]},{tab:{url:'https://evil.test'}});assert.equal(r.ok,false);assert.equal(h.data.catalog,undefined);});
test('official page catalog capture stores normalized public data',async()=>{const h=harness();const r=await h.send({type:'CATALOG_CAPTURE',records:[{url:plan.url,title:'测试',saleText:'开售：2099-09-20 12:00',password:'must-not-store'}]},{tab:{url:'https://search.damai.cn/search.htm'}});assert.equal(r.ok,true);assert.equal(h.data.catalog.length,1);assert.equal(h.data.catalog[0].password,undefined);});
test('invalid plans do not create alarms',async()=>{const h=harness();const r=await h.send({type:'SAVE_PLAN',plan:{...plan,maxTotal:'0'}});assert.equal(r.ok,false);assert.equal(h.alarms.size,0);});
