const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto'),C=require('../extension/catalog.js');
function harness(initial={}){
 const data=structuredClone(initial),alarms=new Map(),notifications=[],opened=[];
 let listener,onAlarm,onStartup,onInstalled,onClick,now=Date.now(),failNotification=false,failAlarm=false;
 class Clock extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const chrome={
  runtime:{getURL:p=>'chrome-extension://test/'+p,getManifest:()=>({version:'0.4.0'}),onMessage:{addListener:f=>listener=f},onStartup:{addListener:f=>onStartup=f},onInstalled:{addListener:f=>onInstalled=f}},
  storage:{local:{setAccessLevel:async()=>{},get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).filter(k=>data[k]!==undefined).map(k=>[k,structuredClone(data[k])])),set:async v=>Object.assign(data,structuredClone(v))}},
  tabs:{query:async()=>[],create:async o=>opened.push(o)},
  alarms:{create:async(id,o)=>{if(failAlarm)throw Error('failed');alarms.set(id,o);},get:async id=>alarms.get(id),getAll:async()=>[...alarms.values()],clear:async id=>alarms.delete(id),onAlarm:{addListener:f=>onAlarm=f}},
  notifications:{create:async(id,o)=>{if(failNotification)throw Error('denied');notifications.push({id,...o});},getPermissionLevel:async()=>failNotification?'denied':'granted',onClicked:{addListener:f=>onClick=f}},
  action:{setBadgeText:async()=>{}},scripting:{executeScript:async()=>{}}
 };
 vm.runInNewContext(fs.readFileSync('extension/background.js','utf8'),{chrome,TicketCatalog:C,TicketPurchase:require('../extension/purchase.js'),TicketPurchaseAdapters:[],importScripts:()=>{},URL,crypto,Date:Clock});
 const send=(msg,sender={url:'chrome-extension://test/ui/dashboard.html'})=>new Promise(resolve=>{const asyncResult=listener(msg,sender,resolve);if(!asyncResult)resolve({ignored:true});});
 return {data,alarms,notifications,opened,send,fire:id=>onAlarm({name:id}),startup:()=>onStartup(),installed:()=>onInstalled(),click:id=>onClick(id),time:t=>now=t,failNotifications:v=>failNotification=v,failAlarms:v=>failAlarm=v};
}
const plan={url:'https://detail.damai.cn/item.htm?id=123456789',title:'测试演出',opensAt:'2099-09-20T12:00',quantity:1,maxTotal:'680',choices:[{session:'周六',tier:'680元'}]};
const stored=(state='scheduled')=>({...C.plan(plan),taskId:'saved',state});
test('saving, firing twice and cancelling reminders is serialized and idempotent',async()=>{const h=harness();const r=await h.send({type:'SAVE_PLAN',plan});assert.equal(r.ok,true);const task=h.data.tasks[0];h.time(task.opensAt);await h.fire(task.taskId);await h.fire(task.taskId);assert.equal(h.notifications.length,1);assert.equal(h.data.tasks[0].state,'notified');await h.send({type:'CANCEL',taskId:task.taskId});assert.equal(h.alarms.size,0);});
test('concurrent identical saves create one reminder',async()=>{const h=harness();const r=await Promise.all([h.send({type:'SAVE_PLAN',plan}),h.send({type:'SAVE_PLAN',plan})]);assert.equal(h.data.tasks.length,1);assert.equal(r[1].duplicate,true);assert.equal(r[0].taskId,r[1].taskId);});
test('different choices preserve separate plans',async()=>{const h=harness();await Promise.all([h.send({type:'SAVE_PLAN',plan}),h.send({type:'SAVE_PLAN',plan:{...plan,choices:[{session:'周日',tier:'480元'}]}})]);assert.equal(h.data.tasks.length,2);});
test('web content cannot create plans or inject offsite catalog',async()=>{const h=harness();await h.send({type:'SAVE_PLAN',plan},{url:plan.url});assert.equal(h.data.tasks,undefined);for(const sender of [{url:'https://evil.test',tab:{url:plan.url}},{url:plan.url,tab:{url:plan.url},frameId:1}]){const r=await h.send({type:'CATALOG_CAPTURE',records:[plan]},sender);assert.equal(r.ok,false);}assert.equal(h.data.catalog,undefined);});
test('official page capture stores normalized public data only',async()=>{const h=harness();const url='https://search.damai.cn/search.htm';const r=await h.send({type:'CATALOG_CAPTURE',records:[null,{url:plan.url,title:'测试',saleText:'开售：2099-09-20 12:00',password:'must-not-store'}]},{url,tab:{url},frameId:0});assert.equal(r.ok,true);assert.equal(h.data.catalog.length,1);assert.equal(h.data.catalog[0].password,undefined);});
test('invalid plans do not create alarms',async()=>{const h=harness();const r=await h.send({type:'SAVE_PLAN',plan:{...plan,maxTotal:'0'}});assert.equal(r.ok,false);assert.equal(h.alarms.size,0);});
test('early alarm reschedules without notifying',async()=>{const h=harness();await h.send({type:'SAVE_PLAN',plan});const task=h.data.tasks[0];await h.fire(task.taskId);assert.equal(h.notifications.length,0);assert.equal(h.data.tasks[0].state,'scheduled');assert.equal(h.alarms.get(task.taskId).when,task.opensAt);});
test('notification failure is visible and explicitly retryable',async()=>{const h=harness();await h.send({type:'SAVE_PLAN',plan});const task=h.data.tasks[0];h.time(task.opensAt);h.failNotifications(true);await h.fire(task.taskId);assert.equal(h.data.tasks[0].state,'notification-failed');await h.startup();assert.equal(h.notifications.length,0);h.failNotifications(false);assert.equal((await h.send({type:'RETRY_NOTIFICATION',taskId:task.taskId})).ok,true);assert.equal(h.data.tasks[0].state,'notified');assert.equal(h.notifications.length,1);assert.equal((await h.send({type:'RETRY_NOTIFICATION',taskId:task.taskId})).ok,false);});
test('worker startup and installation restore missing future alarms only',async()=>{const h=harness({tasks:[stored(),{...stored('cancelled'),taskId:'cancelled'}]});await h.send({type:'DIAGNOSTICS'});assert.equal(h.alarms.size,1);assert.ok(h.alarms.has('saved'));h.alarms.clear();await h.installed();assert.ok(h.alarms.has('saved'));});
test('overdue reminders recover once and interrupted notification remains unknown',async()=>{const old={...stored(),opensAt:Date.now()-1000};const h=harness({tasks:[old,{...stored('notifying'),taskId:'interrupted'}]});await h.send({type:'DIAGNOSTICS'});await h.startup();assert.equal(h.notifications.length,1);assert.equal(h.data.tasks.find(t=>t.taskId==='interrupted').state,'notification-unknown');});
test('alarm creation failure does not report success and can be saved again',async()=>{const h=harness();h.failAlarms(true);assert.equal((await h.send({type:'SAVE_PLAN',plan})).ok,false);assert.equal(h.data.tasks[0].state,'schedule-failed');h.failAlarms(false);assert.equal((await h.send({type:'SAVE_PLAN',plan})).ok,true);assert.equal(h.alarms.size,1);});
test('diagnostics reveal counts and capabilities without personal plan data',async()=>{const h=harness({tasks:[stored()],catalog:[{title:'private-title',url:plan.url,opensAt:123}]});const {ok,report}=await h.send({type:'DIAGNOSTICS'});assert.equal(ok,true);assert.equal(report.taskStates.scheduled,1);assert.equal(report.realCheckoutSupported,false);for(const secret of ['private-title',plan.title,plan.url,'maxTotal','choices'])assert.equal(JSON.stringify(report).includes(secret),false);});
test('notification click never opens an injected offsite URL',async()=>{const h=harness({tasks:[{...stored('notified'),url:'https://evil.test'}]});await h.click('saved');assert.equal(h.opened.length,0);});

test('purchase capabilities report no unsupported real checkout and refuse start',async()=>{const h=harness();const r=await h.send({type:'PURCHASE_STATUS'});assert.equal(r.ok,true);assert.equal(r.adapters.length,0);assert.equal(r.run,null);assert.equal((await h.send({type:'PURCHASE_START',plan:{},tabId:1,adapterId:'damai'})).ok,false);assert.equal(h.data.purchaseLedger,undefined);});
test('ordinary page messages cannot control purchasing',async()=>{const h=harness();const r=await h.send({type:'PURCHASE_START',plan:{},tabId:1,adapterId:'damai'},{url:plan.url,tab:{url:plan.url}});assert.equal(r.ignored,true);assert.equal(h.data.purchaseLedger,undefined);});
test('corrupt purchase records block purchase commands without deleting evidence',async()=>{const h=harness({purchaseLedger:{schema:99,run:{state:'SUBMITTING'}}});assert.equal((await h.send({type:'PURCHASE_STATUS'})).ok,false);assert.equal(h.data.purchaseLedger.schema,99);});
