const {test}=require('node:test'),assert=require('node:assert/strict');
const {Coordinator}=require('../extension/purchase.js');
const plan={itemId:'event-1',choices:['a','b'],quantity:1,maxTotal:68000,opensAt:100,endsAt:10000};
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function fixture(options={}) {
 let db,now=200,seq=0,failWrite=false;const events=[];
 const meta=()=>({source:'official-page',itemId:plan.itemId,tabId:1,observedAt:now});
 const adapter={id:'fixture-only',name:'Test fixture, NOT Damai',supports:()=>true,
  inspect:async()=>({...meta(),schemaOK:true,loginConfirmed:true,existingOrder:false,offers:[{id:'a',status:'available',quantity:1,total:68000},{id:'b',status:'available',quantity:1,total:48000}]}),
  prepare:async action=>{events.push(['prepare',action.id]);adapter.choice=action.id;},
  readCheckout:async()=>({...meta(),schemaOK:true,loginConfirmed:true,existingOrder:false,viewersConfirmed:true,documentId:'checkout-document',choiceId:adapter.choice,quantity:1,total:adapter.choice==='b'?48000:68000}),
  submitOnce:async attempt=>{assert.equal(db.run.state,'SUBMITTING');assert.equal(db.run.attempt.attemptId,attempt.attemptId);events.push(['submit',attempt.choiceId]);},
  reconcile:async t=>({...meta(),authoritative:true,attemptId:t.attemptId,kind:'order',orderId:'order-1',choiceId:t.choiceId,quantity:t.quantity,total:t.total,createdAt:t.at,status:'pending-payment'})
 };
 const config={read:async()=>structuredClone(db),write:async v=>{if(failWrite)throw Error('disk full');db=structuredClone(v);},now:()=>now,id:()=>String(++seq),adapters:[adapter],timeoutMs:options.timeoutMs||1000};
 const c=new Coordinator(config);
 return {c,adapter,events,meta,config,get db(){return db;},set db(v){db=v;},time:t=>now=t,fail:v=>failWrite=v,start:()=>c.start(plan,1,adapter.id)};
}
test('matching official pending order is the only successful purchase outcome',async()=>{const f=fixture(),r=await f.start();const out=await f.c.tick(r.runId);assert.equal(out.state,'SUCCESS');assert.deepEqual(f.events,[['prepare','a'],['submit','a']]);await f.c.tick(r.runId);assert.equal(f.events.length,2);await assert.rejects(f.start());});
test('simultaneous starts across tabs create one persisted task',async()=>{const f=fixture();const rs=await Promise.allSettled([f.start(),f.c.start(plan,2,f.adapter.id)]);assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.db.run.tabId,1);});
test('configuration is copied before the queue and unrelated fields are not stored',async()=>{const f=fixture(),p={...plan,choices:['a','b'],password:'secret'};const pending=f.c.start(p,1,f.adapter.id);p.choices[0]='changed';const r=await pending;assert.deepEqual(r.plan.choices,['a','b']);assert.equal(r.plan.password,undefined);});
test('stale snapshots, wrong event, login and unknown existing orders never prepare',async()=>{for(const patch of [{observedAt:-2000},{itemId:'other'},{loginConfirmed:false},{existingOrder:undefined},{tabId:2},{source:'simulation'}]){const f=fixture(),inspect=f.adapter.inspect;f.adapter.inspect=async()=>({...await inspect(),...patch});const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'PAUSED');assert.equal(f.events.length,0);}});
test('verification, queue and invalid offer structure do not prepare',async()=>{for(const patch of [{blocker:'captcha'},{blocker:'queue'},{schemaOK:false}]){const f=fixture(),inspect=f.adapter.inspect;f.adapter.inspect=async()=>({...await inspect(),...patch});const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'PAUSED');assert.equal(f.events.length,0);}});
test('only explicit soldout allows initial fallback',async()=>{const f=fixture(),inspect=f.adapter.inspect;f.adapter.inspect=async()=>{const s=await inspect();s.offers[0].status='soldout';return s;};const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'SUCCESS');assert.deepEqual(f.events,[['prepare','b'],['submit','b']]);});
test('checkout rechecks identity, totals, viewers and deadline before dispatch',async()=>{for(const patch of [{total:68001},{choiceId:'b'},{quantity:2},{viewersConfirmed:false},{blocker:'captcha'},{documentId:''},{existingOrder:true}]){const f=fixture(),read=f.adapter.readCheckout;f.adapter.readCheckout=async()=>({...await read(),...patch});const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'PAUSED');assert.equal(f.events.filter(x=>x[0]==='submit').length,0);}});
test('expiry during preparation does not dispatch',async()=>{const f=fixture();f.adapter.prepare=async()=>{f.time(11000);f.adapter.choice='a';};const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'PAUSED');assert.equal(f.events.length,0);});
test('failed persistence of submission intent prevents the click',async()=>{const f=fixture(),read=f.adapter.readCheckout;f.adapter.readCheckout=async()=>{f.fail(true);return read();};const r=await f.start();await assert.rejects(f.c.tick(r.runId));assert.equal(f.events.filter(x=>x[0]==='submit').length,0);f.fail(false);const recovered=new Coordinator(f.config);assert.equal((await recovered.recover()).state,'PAUSED');});
test('transport failure still reconciles a successfully created order',async()=>{const f=fixture();f.adapter.submitOnce=async()=>{throw Error('lost response');};const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'SUCCESS');});
test('empty order list is unknown and cannot cause fallback or restart',async()=>{const f=fixture();f.adapter.reconcile=async()=>({kind:'no-order'});const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'UNKNOWN');await f.c.tick(r.runId);assert.equal(f.events.filter(x=>x[0]==='submit').length,1);await assert.rejects(f.start());});
test('mismatched or unproven order never reports success',async()=>{for(const patch of [{attemptId:'other'},{orderId:''},{total:1},{createdAt:1},{status:'processing'},{authoritative:false},{choiceId:'b'}]){const f=fixture(),query=f.adapter.reconcile;f.adapter.reconcile=async t=>({...await query(t),...patch});const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'UNKNOWN');}});
test('final correlated no-order soldout proof permits the next fallback',async()=>{const f=fixture(),query=f.adapter.reconcile;f.adapter.reconcile=async t=>t.choiceId==='a'?({...f.meta(),authoritative:true,attemptId:t.attemptId,kind:'no-order',final:true,reason:'soldout'}):query(t);const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'WAITING');assert.equal((await f.c.tick(r.runId)).state,'SUCCESS');assert.deepEqual(f.events.filter(x=>x[0]==='submit'),[['submit','a'],['submit','b']]);});
test('stop while prepare is awaiting prevents submission and preserves the stop',async()=>{const f=fixture(),entered=deferred(),release=deferred();f.adapter.prepare=async()=>{entered.resolve();await release.promise;};const r=await f.start(),tick=f.c.tick(r.runId);await entered.promise;await f.c.stop(r.runId);release.resolve();assert.equal((await tick).state,'STOPPED');assert.equal(f.events.length,0);});
test('stop during submit does not erase a later confirmed order',async()=>{const f=fixture(),entered=deferred(),release=deferred();f.adapter.submitOnce=async()=>{entered.resolve();await release.promise;};const r=await f.start(),tick=f.c.tick(r.runId);await entered.promise;assert.equal((await f.c.stop(r.runId)).state,'UNKNOWN');await assert.rejects(f.start());release.resolve();assert.equal((await tick).state,'SUCCESS');});
test('parallel ticks never dispatch twice',async()=>{const f=fixture(),r=await f.start();const a=f.c.tick(r.runId);await assert.rejects(f.c.tick(r.runId));await a;assert.equal(f.events.filter(x=>x[0]==='submit').length,1);});
test('worker recovery quarantines an interrupted submission',async()=>{const f=fixture(),r=await f.start();f.adapter.reconcile=async()=>undefined;await f.c.tick(r.runId);f.db.run.state='SUBMITTING';const c=new Coordinator(f.config);assert.equal((await c.recover()).state,'UNKNOWN');await assert.rejects(c.start(plan,1,f.adapter.id));});
test('corrupt ledger and invalid state are never reset into fresh purchases',async()=>{for(const db of [null,{}, {schema:1,run:{state:'BROKEN'}}]){const f=fixture();f.db=db;await assert.rejects(f.start());assert.deepEqual(f.db,db);}});
test('paid order allows a later task but unknown query does not erase confirmed order',async()=>{const f=fixture(),r=await f.start(),query=f.adapter.reconcile;await f.c.tick(r.runId);f.adapter.reconcile=async()=>undefined;assert.equal((await f.c.reconcile(r.runId)).state,'SUCCESS');f.adapter.reconcile=async t=>({...await query(t),status:'paid'});assert.equal((await f.c.reconcile(r.runId)).state,'PAID');assert.equal((await f.start()).state,'WAITING');});
test('stale run messages cannot change a newer run',async()=>{const f=fixture(),r=await f.start();await f.c.stop(r.runId);const next=await f.start();await assert.rejects(f.c.tick(r.runId));assert.equal((await f.c.status()).runId,next.runId);assert.equal((await f.c.status()).state,'WAITING');});
test('submission timeout remains blocked even if the original call is still pending',async()=>{const f=fixture({timeoutMs:10}),release=deferred();f.adapter.submitOnce=()=>release.promise;f.adapter.reconcile=async()=>undefined;const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'UNKNOWN');await assert.rejects(f.start());release.resolve();assert.equal((await f.c.status()).state,'UNKNOWN');});
test('paused task resumes through a new inspection, not a saved checkout',async()=>{const f=fixture(),inspect=f.adapter.inspect;f.adapter.inspect=async()=>({...await inspect(),blocker:'captcha'});const r=await f.start();await f.c.tick(r.runId);f.adapter.inspect=inspect;await f.c.resume(r.runId);assert.equal((await f.c.tick(r.runId)).state,'SUCCESS');});
test('stop during intent storage prevents dispatch even after the write finishes',async()=>{const f=fixture(),entered=deferred(),release=deferred(),write=f.c.write;f.c.write=async db=>{if(db.run?.state==='SUBMITTING'){entered.resolve();await release.promise;}await write(db);};const r=await f.start(),tick=f.c.tick(r.runId);await entered.promise;const stopping=f.c.stop(r.runId);release.resolve();await Promise.all([tick,stopping]);assert.equal(f.events.filter(x=>x[0]==='submit').length,0);assert.equal((await f.c.status()).state,'UNKNOWN');});
test('slow intent storage cannot dispatch against an expired checkout',async()=>{const f=fixture(),write=f.c.write;f.c.write=async db=>{await write(db);if(db.run?.state==='SUBMITTING')f.time(2000);};const r=await f.start();assert.equal((await f.c.tick(r.runId)).state,'UNKNOWN');assert.equal(f.events.filter(x=>x[0]==='submit').length,0);});
